# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20190722_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location']},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='location',
        ),
    ]
