# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20190722_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['submited']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_description',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet,\nagam probatus indoctum cu quo.\nEst eu quod rationibus,\nnam platonem sententiae no.\nEu mel vero oporteat elaboraret.'),
        ),
        migrations.AddField(
            model_name='image',
            name='submited',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='personal.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
